In [1]:
import pandas as pd
import numpy as np

customers = pd.read_csv('customers_raw.csv')

In [2]:
order_items = pd.read_csv('order_items_raw.csv')

In [3]:
orders = pd.read_csv('orders_raw.csv')

In [4]:
products = pd.read_csv('products.csv')

In [5]:
customers.head()

,customer_id,signup_date,age,gender,city,state,customer_segment,acquisition_channel,email_opt_in,loyalty_tier
0,C000001,2024-10-05,NaN,Male,INDORE,Madhya Pradesh,Regular,Organic Search,Yes,Bronze
1,C000002,2025-02-26,23.0,Female,Hyderabad,Telangana,Regular,PPC,Yes,Bronze
2,C000003,2023-01-05,38.0,Male,Bengaluru,Karnataka,Small Business,Paid Social,1,none
3,C000004,2025-10-02,NaN,Female,Lucknow,uttar pradesh,Regular,Paid Social,Yes,Bronze
4,C000005,2025-02-04,30.0,Female,delhi,DL,Regular,Direct,Yes,Bronze

In [6]:
cs = customers

In [7]:
cs[cs['signup_date'].isnull()]

,customer_id,signup_date,age,gender,city,state,customer_segment,acquisition_channel,email_opt_in,loyalty_tier
8,C000009,NaN,25.0,Other,Amritsar,Punjab,Bargain Hunter,Paid Social,Y,Bronze
155,C000145,NaN,33.0,Male,Coimbatore,NaN,Regular,organic_search,No,Silver
192,C000180,NaN,NaN,female,Delhi,Delhi,Student,Paid Search,Yes,Bronze
415,C000387,NaN,44.0,male,Bangalore,Karnataka,Premium,Affiliate,Yes,Bronze
571,C000531,NaN,49.0,Male,Kolkata,West Bengal,Bargain Hunter,Direct,No,Gold
...,...,...,...,...,...,...,...,...,...,...
11983,C011219,NaN,86.0,Female,Surat,Gujarat,Premium,Direct,Yes,Gold
12054,C011286,NaN,29.0,Male,Visakhapatnam,Andhra Pradesh,Regular,organic search,Yes,NaN
12356,C011563,NaN,52.0,Male,Mumbai,MH,Regular,Referral,Yes,Bronze
12365,C004760,NaN,31.0,NaN,Delhi,Delhi,REGULAR,Email Marketing,Yes,Gold
12386,C011590,NaN,31.0,Female,Jaipur,Rajasthan,Bargain Hunter,Paid Search,1,Silver

In [8]:
cs.info()

<class 'pandas.DataFrame'>
RangeIndex: 12400 entries, 0 to 12399
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          12400 non-null  str
 1   signup_date          12242 non-null  str
 2   age                  11945 non-null  float64
 3   gender               12010 non-null  str
 4   city                 12009 non-null  str
 5   state                11957 non-null  str
 6   customer_segment     12069 non-null  str
 7   acquisition_channel  12102 non-null  str
 8   email_opt_in         12155 non-null  str
 9   loyalty_tier         9422 non-null   str
dtypes: float64(1), str(9)
memory usage: 968.9 KB

In [9]:
cs.duplicated().sum()

np.int64(314)

In [10]:
cs['customer_id'].duplicated().sum()

np.int64(800)

In [11]:
cs[cs['customer_id'].duplicated(keep=False)].sort_values('customer_id')

,customer_id,signup_date,age,gender,city,state,customer_segment,acquisition_channel,email_opt_in,loyalty_tier
2,C000003,2023-01-05,38.0,Male,Bengaluru,Karnataka,Small Business,Paid Social,1,none
2318,C000003,2023-01-05,38.0,Male,Bengaluru,Karnataka,Small Business,NaN,1,none
176,C000003,2023-01-05,38.0,Male,Bengaluru,Karnataka,Small Business,Paid Social,1,none
46,C000042,23/11/2025,18.0,Male,Thiruvananthapuram,Kerala,Regular,Paid Search,N,NaN
3010,C000042,23/11/2025,18.0,Male,Thiruvananthapuram,Kerala,Regular,Paid Search,N,None
...,...,...,...,...,...,...,...,...,...,...
11147,C011335,2025-06-02,40.0,male,Mumbai,Maharashtra,Small Business,Organic Search,True,Platinum
12167,C011388,15/07/2025,49.0,Female,Bengaluru,Karnataka,NaN,direct,Y,NaN
10415,C011388,15/07/2025,49.0,FEMALE,Bengaluru,Karnataka,NaN,direct,Y,NaN
12284,C011496,2023-12-03,34.0,FEMALE,Visakhapatnam,ANDHRA PRADESH,Bargain Hunter,Paid Social,No,Gold
1991,C011496,2023-12-03,34.0,FEMALE,Visakhapatnam,ANDHRA PRADESH,Bargain Hunter,Paid Social,No,Gold

In [12]:
cs['gender'].unique()

<StringArray>
[      'Male',     'Female',      'Other',     'FEMALE',       'male',
     'female',          nan,          'F',       'MALE',          'M',
 'Non-binary',      'Male ',    'Female ',      'other',          'O',
         'M ']
Length: 16, dtype: str

In [13]:
cs['gender'] = cs['gender'].replace({'male','M','MALE','Male ','M '},'Male')

In [14]:
cs['gender'] = cs['gender'].replace({'female','F','FEMALE','Female ','F '},'Female')

In [15]:
cs['gender'] = cs['gender'].replace({'other','O'},'Other')

In [16]:
cs['customer_id'].duplicated().sum()

np.int64(800)

In [17]:
cs.loc[
    cs['city'].str.startswith(('Mu','mu'), na=False),
    'city'
].unique()

<StringArray>
['Mumbai', 'Mumbai ', 'mumbai']
Length: 3, dtype: str

In [18]:
cs['city'] = cs['city'].str.strip().str.title()

In [19]:
cs['city'].unique()

<StringArray>
[            'Indore',          'Hyderabad',          'Bengaluru',
            'Lucknow',              'Delhi',            'Kolkata',
          'Ahmedabad',           'Amritsar',             'Mumbai',
              'Surat',             'Panaji',               'Pune',
             'Nagpur',             'Jaipur',           'Ludhiana',
      'Visakhapatnam',             'Nashik',            'Chennai',
                  nan,            'Madurai',             'Bhopal',
              'Noida',         'Chandigarh',             'Mysuru',
             'Kanpur', 'Thiruvananthapuram',           'Varanasi',
        'Vasai-Virar',         'Coimbatore',            'Jodhpur',
          'New Delhi',              'Kochi',               'Agra',
           'Dehradun',        'Bhubaneswar',              'Patna',
           'Guwahati',           'Vadodara',             'Raipur',
             'Ranchi',           'Gurugram',            'Gurgaon',
           'Calcutta',          'Bangalore',              'Poona',
             'Mysore',             'Cochin',             'Baroda',
             'Bombay',              'Vizag',             'Madras',
         'Trivandrum']
Length: 52, dtype: str

In [20]:
cs['city'] = cs['city'].replace('Bombay','Mumbai')

In [21]:
cs['city'] = cs['city'].replace('New Delhi','Delhi')

In [22]:
cs['city'] = cs['city'].replace('Gurgaon','Gurugram')

In [23]:
cs['city'] = cs['city'].replace('Calcutta','Kolkata')

In [24]:
cs['city'] = cs['city'].replace('Poona','Pune')

In [25]:
cs['city'] = cs['city'].replace('Baroda','Vadodara')

In [26]:
cs['city'] = cs['city'].replace('Cochin','Kochi')

In [27]:
sorted(cs['city'].dropna().unique())

['Agra',
 'Ahmedabad',
 'Amritsar',
 'Bangalore',
 'Bengaluru',
 'Bhopal',
 'Bhubaneswar',
 'Chandigarh',
 'Chennai',
 'Coimbatore',
 'Dehradun',
 'Delhi',
 'Gurugram',
 'Guwahati',
 'Hyderabad',
 'Indore',
 'Jaipur',
 'Jodhpur',
 'Kanpur',
 'Kochi',
 'Kolkata',
 'Lucknow',
 'Ludhiana',
 'Madras',
 'Madurai',
 'Mumbai',
 'Mysore',
 'Mysuru',
 'Nagpur',
 'Nashik',
 'Noida',
 'Panaji',
 'Patna',
 'Pune',
 'Raipur',
 'Ranchi',
 'Surat',
 'Thiruvananthapuram',
 'Trivandrum',
 'Vadodara',
 'Varanasi',
 'Vasai-Virar',
 'Visakhapatnam',
 'Vizag']

In [28]:
city_mapping = {
    'Bangalore': 'Bengaluru',
    'Mysore': 'Mysuru',
    'Madras': 'Chennai',
    'Trivandrum': 'Thiruvananthapuram',
    'Vizag': 'Visakhapatnam',
    'Gurgaon': 'Gurugram',
    'Baroda': 'Vadodara',
    'Cochin': 'Kochi'
}

cs['city'] = cs['city'].str.strip().replace(city_mapping)

In [29]:
cs

,customer_id,signup_date,age,gender,city,state,customer_segment,acquisition_channel,email_opt_in,loyalty_tier
0,C000001,2024-10-05,NaN,Male,Indore,Madhya Pradesh,Regular,Organic Search,Yes,Bronze
1,C000002,2025-02-26,23.0,Female,Hyderabad,Telangana,Regular,PPC,Yes,Bronze
2,C000003,2023-01-05,38.0,Male,Bengaluru,Karnataka,Small Business,Paid Social,1,none
3,C000004,2025-10-02,NaN,Female,Lucknow,uttar pradesh,Regular,Paid Social,Yes,Bronze
4,C000005,2025-02-04,30.0,Female,Delhi,DL,Regular,Direct,Yes,Bronze
...,...,...,...,...,...,...,...,...,...,...
12395,C002039,11/10/2025,NaN,Female,Dehradun,Uttarakhand,Premium,PPC,True,bronze
12396,C011598,03-Dec-2025,37.0,Male,Bhubaneswar,Odisha,Bargain Hunter,Direct,Yes,NaN
12397,C011599,2023-11-22,31.0,Female,Mumbai,Maharashtra,Regular,Paid Social,1,Silver
12398,C011600,2026-04-25,46.0,Female,Chennai,Tamil Nadu,Regular,Organic Search,Yes,Bronze
12399,C006117,2025-08-30,NaN,Female,Delhi,Delhi,Regular,Email Marketing,Yes,BRONZE

In [30]:
for col in cs.columns:
    print(f"\nColumn: {col}")
    print(cs[col].unique())

Column: customer_id
<StringArray>
['C000001', 'C000002', 'C000003', 'C000004', 'C000005', 'C000006', 'C000007',
 'C000008', 'C000009', 'C000010',
 ...
 'C011591', 'C011592', 'C011593', 'C011594', 'C011595', 'C011596', 'C011597',
 'C011598', 'C011599', 'C011600']
Length: 11600, dtype: str

Column: signup_date
<StringArray>
[ '2024-10-05',  '2025-02-26',  '2023-01-05',  '2025-10-02',  '2025-02-04',
  '2023/05/19',  '18/05/2023',  '2023-01-25',           nan,  '2025-03-22',
 ...
  '17/05/2025',  '2023/10/10',  '16/06/2025',  '23/03/2025',  '13/10/2024',
 '25-Dec-2023',  '14/12/2025',  '28/12/2024',  '24/11/2024', '03-Dec-2025']
Length: 3043, dtype: str

Column: age
[ nan  23.  38.  30.  52.  27.  24.  25.  35.  20.  21.  22.  18.  26.
  39.  34.  29.  43.  36.  19.  41. 150.  45.  46.  28.  31.   0.  32.
  37.  48.  93.  88.  40.  44.  33.  50.  57.  42.  58.  51.  49.  55.
  47.  53.  56.   5.  98. 999.  54.  94.  12.  -3.  85.  59.  62.  90.
  89.  61.  63. 118.  64.  92.  96.  86.  65.  87.  70.  95.]

Column: gender
<StringArray>
['Male', 'Female', 'Other', nan, 'Non-binary']
Length: 5, dtype: str

Column: city
<StringArray>
[            'Indore',          'Hyderabad',          'Bengaluru',
            'Lucknow',              'Delhi',            'Kolkata',
          'Ahmedabad',           'Amritsar',             'Mumbai',
              'Surat',             'Panaji',               'Pune',
             'Nagpur',             'Jaipur',           'Ludhiana',
      'Visakhapatnam',             'Nashik',            'Chennai',
                  nan,            'Madurai',             'Bhopal',
              'Noida',         'Chandigarh',             'Mysuru',
             'Kanpur', 'Thiruvananthapuram',           'Varanasi',
        'Vasai-Virar',         'Coimbatore',            'Jodhpur',
              'Kochi',               'Agra',           'Dehradun',
        'Bhubaneswar',              'Patna',           'Guwahati',
           'Vadodara',             'Raipur',             'Ranchi',
           'Gurugram']
Length: 40, dtype: str

Column: state
<StringArray>
[ 'Madhya Pradesh',       'Telangana',       'Karnataka',   'uttar pradesh',
              'DL',     'West Bengal',         'Gujarat',          'Punjab',
     'MAHARASHTRA',             'Goa',     'Maharashtra',       'Rajasthan',
              'AP',              'KA',           'Delhi',      'Tamil Nadu',
   'Uttar Pradesh',      'Chandigarh',          'Kerala',               nan,
           'DELHI',              'UP',       'telangana',  'Andhra Pradesh',
         'gujarat',   'UTTAR PRADESH',          'Odisha',  'MADHYA PRADESH',
           'Bihar',     'west bengal',              'GJ',       'KARNATAKA',
           'Assam',     'Uttarakhand',    'Chhattisgarh',              'TN',
         'Haryana',      'CHANDIGARH',       'Jharkhand',    'Maharashtra ',
              'PB',          'kerala',     'maharashtra',         'GUJARAT',
              'MH',     'WEST BENGAL',           'ASSAM',          'Assam ',
              'CG',              'MP',    'West Bengal ',       'TELANGANA',
           'delhi',       'RAJASTHAN',              'RJ',          'KERALA',
       'karnataka',          'PUNJAB',         'HARYANA',      'tamil nadu',
         'haryana',    'CHHATTISGARH',      'TAMIL NADU',  'ANDHRA PRADESH',
              'TS',      'Telangana ',              'KL',      'chandigarh',
       'rajasthan',           'BIHAR',       'jharkhand',              'BR',
              'AS',  'andhra pradesh',              'JH',          'Delhi ',
          'punjab',  'madhya pradesh',             'MP ',              'WB',
             'GOA',              'HR',           'bihar',     'TAMIL NADU ',
        'Gujarat ',              'UK',              'GA',          'odisha',
              'CH',              'OD',      'Rajasthan ',  'Uttar Pradesh ',
 'Madhya Pradesh ',      'KARNATAKA ',       'JHARKHAND',           'assam']
Length: 96, dtype: str

Column: customer_segment
<StringArray>
[        'Regular',  'Small Business',         'Premium',         'Student',
  'Bargain Hunter',       'Small Biz',               nan,         'REGULAR',
     'Deal Seeker',  'bargain hunter',         'regular',        'Premium ',
         'STUDENT',         'PREMIUM',         'student',  'Bargain hunter',
         'premium',  'small business',             'SMB',  'SMALL BUSINESS',
  'BARGAIN HUNTER',        'Regular ',        'REGULAR ', 'Bargain Hunter ',
        'Student ', 'Small Business ', 'bargain hunter ',        'regular ',
        'STUDENT ']
Length: 29, dtype: str

Column: acquisition_channel
<StringArray>
[ 'Organic Search',             'PPC',     'Paid Social',          'Direct',
        'Referral',     'Paid Search',      'Social Ads',       'Affiliate',
 'Email Marketing',           'Email',               nan, 'email marketing',
     'paid_search',        'REFERRAL',          'direct',      'Affiliates',
     'paid_social',     'paid search',          'DIRECT',           'email',
       'Referrals',         'direct ',  'organic_search',     'Paid search',
       'AFFILIATE',        'referral',     'paid social',          'E-mail',
  'ORGANIC SEARCH',         'Organic',    'Paid Social ',       'affiliate',
  'Direct Traffic',      'affiliate ',  'organic search',  'Refer-a-Friend']
Length: 36, dtype: str

Column: email_opt_in
<StringArray>
['Yes', '1', 'No', 'Y', nan, 'False', 'yes', 'N', 'no', 'True', '0']
Length: 11, dtype: str

Column: loyalty_tier
<StringArray>
[   'Bronze',      'none',      'Gold',         nan,    'bronze',    'BRONZE',
    'Silver',  'Platinum',   'No Tier',      'GOLD',    'SILVER',    'silver',
      'Plat',      'NONE',      'gold',   'SILVER ',  'PLATINUM',  'platinum',
   'BRONZE ',   'Bronze ',   'Silver ',     'None ',     'Gold ', 'Platinum ',
   'bronze ']
Length: 25, dtype: str

In [31]:
df = cs

In [32]:
df['state'].unique()

<StringArray>
[ 'Madhya Pradesh',       'Telangana',       'Karnataka',   'uttar pradesh',
              'DL',     'West Bengal',         'Gujarat',          'Punjab',
     'MAHARASHTRA',             'Goa',     'Maharashtra',       'Rajasthan',
              'AP',              'KA',           'Delhi',      'Tamil Nadu',
   'Uttar Pradesh',      'Chandigarh',          'Kerala',               nan,
           'DELHI',              'UP',       'telangana',  'Andhra Pradesh',
         'gujarat',   'UTTAR PRADESH',          'Odisha',  'MADHYA PRADESH',
           'Bihar',     'west bengal',              'GJ',       'KARNATAKA',
           'Assam',     'Uttarakhand',    'Chhattisgarh',              'TN',
         'Haryana',      'CHANDIGARH',       'Jharkhand',    'Maharashtra ',
              'PB',          'kerala',     'maharashtra',         'GUJARAT',
              'MH',     'WEST BENGAL',           'ASSAM',          'Assam ',
              'CG',              'MP',    'West Bengal ',       'TELANGANA',
           'delhi',       'RAJASTHAN',              'RJ',          'KERALA',
       'karnataka',          'PUNJAB',         'HARYANA',      'tamil nadu',
         'haryana',    'CHHATTISGARH',      'TAMIL NADU',  'ANDHRA PRADESH',
              'TS',      'Telangana ',              'KL',      'chandigarh',
       'rajasthan',           'BIHAR',       'jharkhand',              'BR',
              'AS',  'andhra pradesh',              'JH',          'Delhi ',
          'punjab',  'madhya pradesh',             'MP ',              'WB',
             'GOA',              'HR',           'bihar',     'TAMIL NADU ',
        'Gujarat ',              'UK',              'GA',          'odisha',
              'CH',              'OD',      'Rajasthan ',  'Uttar Pradesh ',
 'Madhya Pradesh ',      'KARNATAKA ',       'JHARKHAND',           'assam']
Length: 96, dtype: str

In [33]:
df['state'] = df['state'].str.strip().str.title()

In [34]:
df['state'] = df['state'].replace('Mp','Madhya Pradesh')

In [35]:
state_mapping = {
    'Dl': 'Delhi',
    'Ap': 'Andhra Pradesh',
    'Ka': 'Karnataka',
    'Up': 'Uttar Pradesh',
    'Gj': 'Gujarat',
    'Tn': 'Tamil Nadu',
    'Pb': 'Punjab',
    'Mh': 'Maharashtra',
    'Cg': 'Chhattisgarh',
    'Rj': 'Rajasthan',
    'Ts': 'Telangana',
    'Kl': 'Kerala',
    'Br': 'Bihar',
    'As': 'Assam',
    'Jh': 'Jharkhand',
    'Wb': 'West Bengal',
    'Hr': 'Haryana',
    'Uk': 'Uttarakhand',
    'Ga': 'Goa',
    'Ch': 'Chandigarh',
    'Od': 'Odisha'
}

df['state'] = df['state'].replace(state_mapping)

In [36]:
df['customer_segment'].unique()

<StringArray>
[        'Regular',  'Small Business',         'Premium',         'Student',
  'Bargain Hunter',       'Small Biz',               nan,         'REGULAR',
     'Deal Seeker',  'bargain hunter',         'regular',        'Premium ',
         'STUDENT',         'PREMIUM',         'student',  'Bargain hunter',
         'premium',  'small business',             'SMB',  'SMALL BUSINESS',
  'BARGAIN HUNTER',        'Regular ',        'REGULAR ', 'Bargain Hunter ',
        'Student ', 'Small Business ', 'bargain hunter ',        'regular ',
        'STUDENT ']
Length: 29, dtype: str

In [37]:
df['customer_segment'] = df['customer_segment'].str.strip().str.title()

In [38]:
df['customer_segment'] = df['customer_segment'].replace({'Small Biz','Smb'},'Small Business')

In [39]:
df['acquisition_channel'].unique()

<StringArray>
[ 'Organic Search',             'PPC',     'Paid Social',          'Direct',
        'Referral',     'Paid Search',      'Social Ads',       'Affiliate',
 'Email Marketing',           'Email',               nan, 'email marketing',
     'paid_search',        'REFERRAL',          'direct',      'Affiliates',
     'paid_social',     'paid search',          'DIRECT',           'email',
       'Referrals',         'direct ',  'organic_search',     'Paid search',
       'AFFILIATE',        'referral',     'paid social',          'E-mail',
  'ORGANIC SEARCH',         'Organic',    'Paid Social ',       'affiliate',
  'Direct Traffic',      'affiliate ',  'organic search',  'Refer-a-Friend']
Length: 36, dtype: str

In [40]:
df['acquisition_channel'] = df['acquisition_channel'].str.strip().str.title()

In [41]:
channel_mapping = {
    'Ppc': 'Paid Search',
    'Paid_Search': 'Paid Search',
    'Organic_Search': 'Organic Search',
    'Organic': 'Organic Search',
    'Social Ads': 'Paid Social',
    'Paid_Social': 'Paid Social',
    'Email': 'Email Marketing',
    'E-Mail': 'Email Marketing',
    'Affiliates': 'Affiliate',
    'Referrals': 'Referral',
    'Refer-A-Friend': 'Referral',
    'Direct Traffic': 'Direct'
}

df['acquisition_channel'] = (
    df['acquisition_channel']
    .str.strip()
    .replace(channel_mapping)
)

In [42]:
df['email_opt_in'].unique()

<StringArray>
['Yes', '1', 'No', 'Y', nan, 'False', 'yes', 'N', 'no', 'True', '0']
Length: 11, dtype: str

In [43]:
boolean_mapping = {
    'Yes': 'Yes',
    'yes': 'Yes',
    'Y': 'Yes',
    '1': 'Yes',
    'True': 'Yes',
    'No': 'No',
    'no': 'No',
    'N': 'No',
    '0': 'No',
    'False': 'No'
}

col = 'email_opt_in'

df[col] = (
    df[col]
    .astype('string')
    .str.strip()
    .replace(boolean_mapping)
)

In [44]:
df['loyalty_tier'].unique()

<StringArray>
[   'Bronze',      'none',      'Gold',         nan,    'bronze',    'BRONZE',
    'Silver',  'Platinum',   'No Tier',      'GOLD',    'SILVER',    'silver',
      'Plat',      'NONE',      'gold',   'SILVER ',  'PLATINUM',  'platinum',
   'BRONZE ',   'Bronze ',   'Silver ',     'None ',     'Gold ', 'Platinum ',
   'bronze ']
Length: 25, dtype: str

In [45]:
df['loyalty_tier'] = (
    df['loyalty_tier']
    .str.strip()
    .str.title()
    .replace({
        'Plat': 'Platinum',
        'None': 'No Tier'
    })
)

In [46]:
df[df.duplicated(keep=False)].sort_values('customer_id')

,customer_id,signup_date,age,gender,city,state,customer_segment,acquisition_channel,email_opt_in,loyalty_tier
2,C000003,2023-01-05,38.0,Male,Bengaluru,Karnataka,Small Business,Paid Social,Yes,No Tier
176,C000003,2023-01-05,38.0,Male,Bengaluru,Karnataka,Small Business,Paid Social,Yes,No Tier
1014,C000063,31-May-2025,31.0,Male,Nashik,NaN,Premium,Paid Search,<NA>,Silver
69,C000063,31-May-2025,31.0,Male,Nashik,NaN,Premium,Paid Search,<NA>,Silver
84,C000077,2024-08-18,45.0,Male,Bengaluru,Karnataka,Regular,Paid Social,No,Bronze
...,...,...,...,...,...,...,...,...,...,...
12106,C011335,2025-06-02,40.0,Male,Mumbai,Maharashtra,Small Business,Organic Search,Yes,Platinum
12167,C011388,15/07/2025,49.0,Female,Bengaluru,Karnataka,NaN,Direct,Yes,NaN
10415,C011388,15/07/2025,49.0,Female,Bengaluru,Karnataka,NaN,Direct,Yes,NaN
1991,C011496,2023-12-03,34.0,Female,Visakhapatnam,Andhra Pradesh,Bargain Hunter,Paid Social,No,Gold
12284,C011496,2023-12-03,34.0,Female,Visakhapatnam,Andhra Pradesh,Bargain Hunter,Paid Social,No,Gold

In [47]:
df = df.drop_duplicates()

In [48]:
df.describe()

                age
count  11395.000000
mean      31.842211
std       30.543035
min       -3.000000
25%       23.000000
50%       30.000000
75%       37.000000
max      999.000000

In [49]:
df.describe(include='all')

,customer_id,signup_date,age,gender,city,state,customer_segment,acquisition_channel,email_opt_in,loyalty_tier
count,11834,11683,11395.000000,11466,11456,11407,11521,11544,11598,8990
unique,11600,3042,NaN,4,39,22,6,7,2,5
top,C002769,2026-04-10,NaN,Male,Mumbai,Maharashtra,Regular,Organic Search,Yes,Bronze
freq,3,20,NaN,5975,1164,2238,5289,2804,7190,4549
mean,NaN,NaN,31.842211,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,30.543035,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,-3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,23.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,30.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,37.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,999.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
df[df['age']>90]

,customer_id,signup_date,age,gender,city,state,customer_segment,acquisition_channel,email_opt_in,loyalty_tier
50,C000046,2026-05-31,150.0,Female,Chennai,Tamil Nadu,Bargain Hunter,Direct,Yes,Bronze
93,C000083,2025-06-05,93.0,Female,Noida,Uttar Pradesh,Bargain Hunter,Referral,No,Bronze
558,C000518,2023-12-05,98.0,Female,Bengaluru,Karnataka,Student,Affiliate,No,Bronze
893,C000833,2025-09-15,999.0,Male,Ahmedabad,Gujarat,Small Business,Affiliate,No,NaN
971,C000905,2026-02-12,150.0,Female,Vadodara,Gujarat,Student,Paid Search,Yes,NaN
1054,C000982,2026-01-04,150.0,Female,Dehradun,Uttarakhand,Student,Organic Search,Yes,NaN
1070,C000997,2025-10-27,93.0,Female,Pune,Maharashtra,Regular,Paid Social,No,NaN
1236,C001153,2024-01-31,94.0,Male,Hyderabad,Telangana,Premium,Referral,Yes,Bronze
1704,C001588,24/05/2026,999.0,Female,Delhi,Delhi,Regular,Direct,No,Bronze
1829,C001703,15-Dec-2024,93.0,Male,Bhopal,Madhya Pradesh,NaN,Paid Search,No,Bronze
3733,C003483,2024-02-05,118.0,Male,Nagpur,Maharashtra,Regular,Affiliate,Yes,NaN
3758,C003506,25/07/2023,94.0,Female,Gurugram,Haryana,NaN,Affiliate,Yes,Bronze
3762,C003510,2024-02-27,999.0,Male,Bhopal,Madhya Pradesh,Regular,Email Marketing,Yes,Platinum
3772,C003520,15/02/2026,118.0,Other,Hyderabad,Telangana,Regular,Organic Search,No,Bronze
3871,C003615,28/08/2024,92.0,Female,Guwahati,Assam,Regular,Email Marketing,No,Gold
4476,C004190,2026/05/01,999.0,Female,Coimbatore,Tamil Nadu,Student,Organic Search,No,NaN
4853,C004529,2024-08-05,118.0,Female,Ludhiana,Punjab,Regular,Organic Search,Yes,Bronze
5094,C004753,2025-09-23,96.0,Female,Madurai,Tamil Nadu,Regular,Direct,Yes,Silver
5137,C004794,11/10/2023,999.0,Male,Ludhiana,Punjab,Regular,Direct,Yes,Bronze
5365,C005009,2024-02-30,92.0,Female,Pune,Maharashtra,Regular,Paid Search,Yes,Platinum
6164,C005757,20-May-2026,118.0,Female,Lucknow,Uttar Pradesh,Regular,Referral,Yes,NaN
6204,C005796,2023-12-07,999.0,Male,Coimbatore,Tamil Nadu,Student,Paid Search,Yes,NaN
6536,C006116,12-Feb-2026,150.0,Male,Chennai,Tamil Nadu,Premium,Organic Search,Yes,Gold
6702,C006275,09/02/2024,999.0,Female,Delhi,Delhi,Premium,Direct,No,NaN
6745,C006316,2025-05-03,98.0,Male,Mumbai,Maharashtra,Regular,Email Marketing,Yes,NaN
6934,C006493,2024-07-29,150.0,Male,Delhi,Delhi,Regular,Direct,Yes,Gold
7352,C006885,2024-02-23,150.0,Male,Mumbai,Maharashtra,Premium,Direct,No,No Tier
7390,C006921,2026-06-13,118.0,Male,Mumbai,Maharashtra,Regular,NaN,No,NaN
7423,C006954,06/01/2024,150.0,Male,Mumbai,Maharashtra,Small Business,Paid Search,No,NaN
7872,C007382,26/06/2026,999.0,Male,Kochi,Kerala,Regular,Organic Search,Yes,NaN
7891,C007398,26/12/2025,94.0,Male,Coimbatore,Tamil Nadu,Premium,Paid Search,Yes,Bronze
7900,C007407,2025-08-26,118.0,Male,Kolkata,West Bengal,Regular,Organic Search,No,NaN
8068,C007565,2023-06-09,999.0,Female,Bhopal,Madhya Pradesh,Regular,Email Marketing,No,Platinum
8406,C007877,2025-09-17,118.0,Male,NaN,Chandigarh,Regular,Direct,No,Gold
8614,C008069,2026-02-15,118.0,Female,Ahmedabad,Gujarat,Regular,Paid Social,Yes,NaN
8782,C008223,2023-11-03,98.0,Female,Pune,Maharashtra,Regular,Organic Search,Yes,NaN
8900,C008335,19-Feb-2026,96.0,Male,Bhopal,Madhya Pradesh,Regular,Email Marketing,Yes,Silver
9277,C008684,2025-04-15,150.0,Female,Delhi,Delhi,Regular,Affiliate,No,Bronze
10412,C009753,2025-12-07,150.0,Male,Bengaluru,Karnataka,Regular,Direct,Yes,Bronze
11305,C010589,2026-05-30,94.0,Female,Jaipur,Rajasthan,Small Business,Paid Social,Yes,NaN
11419,C010697,NaN,95.0,Female,Agra,Uttar Pradesh,Regular,Paid Search,No,Bronze
11474,C010751,2025-05-05,98.0,Female,Kochi,Kerala,Regular,Direct,<NA>,NaN
11590,C010853,2024-09-28,118.0,Male,Bengaluru,Karnataka,Regular,Paid Search,Yes,Gold
11650,C010909,2026-05-25,118.0,Male,Indore,Madhya Pradesh,Regular,Email Marketing,No,NaN
11746,C010996,2026-01-04,118.0,Male,Bengaluru,Karnataka,Student,Affiliate,Yes,Bronze
11840,C011086,2026-05-07,150.0,Female,Mumbai,Maharashtra,Premium,Paid Search,Yes,Silver
12340,C011548,2023-01-18,96.0,Male,Ahmedabad,Gujarat,Regular,Referral,Yes,Silver
12389,C011593,2023-07-10,999.0,NaN,Mumbai,Maharashtra,Small Business,Paid Social,Yes,Silver

In [51]:
df[df['age'] > 90].sort_values('age')

,customer_id,signup_date,age,gender,city,state,customer_segment,acquisition_channel,email_opt_in,loyalty_tier
3871,C003615,28/08/2024,92.0,Female,Guwahati,Assam,Regular,Email Marketing,No,Gold
5365,C005009,2024-02-30,92.0,Female,Pune,Maharashtra,Regular,Paid Search,Yes,Platinum
1829,C001703,15-Dec-2024,93.0,Male,Bhopal,Madhya Pradesh,NaN,Paid Search,No,Bronze
93,C000083,2025-06-05,93.0,Female,Noida,Uttar Pradesh,Bargain Hunter,Referral,No,Bronze
1070,C000997,2025-10-27,93.0,Female,Pune,Maharashtra,Regular,Paid Social,No,NaN
1236,C001153,2024-01-31,94.0,Male,Hyderabad,Telangana,Premium,Referral,Yes,Bronze
7891,C007398,26/12/2025,94.0,Male,Coimbatore,Tamil Nadu,Premium,Paid Search,Yes,Bronze
3758,C003506,25/07/2023,94.0,Female,Gurugram,Haryana,NaN,Affiliate,Yes,Bronze
11305,C010589,2026-05-30,94.0,Female,Jaipur,Rajasthan,Small Business,Paid Social,Yes,NaN
11419,C010697,NaN,95.0,Female,Agra,Uttar Pradesh,Regular,Paid Search,No,Bronze
5094,C004753,2025-09-23,96.0,Female,Madurai,Tamil Nadu,Regular,Direct,Yes,Silver
12340,C011548,2023-01-18,96.0,Male,Ahmedabad,Gujarat,Regular,Referral,Yes,Silver
8900,C008335,19-Feb-2026,96.0,Male,Bhopal,Madhya Pradesh,Regular,Email Marketing,Yes,Silver
6745,C006316,2025-05-03,98.0,Male,Mumbai,Maharashtra,Regular,Email Marketing,Yes,NaN
558,C000518,2023-12-05,98.0,Female,Bengaluru,Karnataka,Student,Affiliate,No,Bronze
8782,C008223,2023-11-03,98.0,Female,Pune,Maharashtra,Regular,Organic Search,Yes,NaN
11474,C010751,2025-05-05,98.0,Female,Kochi,Kerala,Regular,Direct,<NA>,NaN
8614,C008069,2026-02-15,118.0,Female,Ahmedabad,Gujarat,Regular,Paid Social,Yes,NaN
6164,C005757,20-May-2026,118.0,Female,Lucknow,Uttar Pradesh,Regular,Referral,Yes,NaN
7390,C006921,2026-06-13,118.0,Male,Mumbai,Maharashtra,Regular,NaN,No,NaN
3772,C003520,15/02/2026,118.0,Other,Hyderabad,Telangana,Regular,Organic Search,No,Bronze
11590,C010853,2024-09-28,118.0,Male,Bengaluru,Karnataka,Regular,Paid Search,Yes,Gold
11746,C010996,2026-01-04,118.0,Male,Bengaluru,Karnataka,Student,Affiliate,Yes,Bronze
11650,C010909,2026-05-25,118.0,Male,Indore,Madhya Pradesh,Regular,Email Marketing,No,NaN
8406,C007877,2025-09-17,118.0,Male,NaN,Chandigarh,Regular,Direct,No,Gold
4853,C004529,2024-08-05,118.0,Female,Ludhiana,Punjab,Regular,Organic Search,Yes,Bronze
7900,C007407,2025-08-26,118.0,Male,Kolkata,West Bengal,Regular,Organic Search,No,NaN
3733,C003483,2024-02-05,118.0,Male,Nagpur,Maharashtra,Regular,Affiliate,Yes,NaN
1054,C000982,2026-01-04,150.0,Female,Dehradun,Uttarakhand,Student,Organic Search,Yes,NaN
7352,C006885,2024-02-23,150.0,Male,Mumbai,Maharashtra,Premium,Direct,No,No Tier
7423,C006954,06/01/2024,150.0,Male,Mumbai,Maharashtra,Small Business,Paid Search,No,NaN
6934,C006493,2024-07-29,150.0,Male,Delhi,Delhi,Regular,Direct,Yes,Gold
6536,C006116,12-Feb-2026,150.0,Male,Chennai,Tamil Nadu,Premium,Organic Search,Yes,Gold
971,C000905,2026-02-12,150.0,Female,Vadodara,Gujarat,Student,Paid Search,Yes,NaN
50,C000046,2026-05-31,150.0,Female,Chennai,Tamil Nadu,Bargain Hunter,Direct,Yes,Bronze
9277,C008684,2025-04-15,150.0,Female,Delhi,Delhi,Regular,Affiliate,No,Bronze
11840,C011086,2026-05-07,150.0,Female,Mumbai,Maharashtra,Premium,Paid Search,Yes,Silver
10412,C009753,2025-12-07,150.0,Male,Bengaluru,Karnataka,Regular,Direct,Yes,Bronze
3762,C003510,2024-02-27,999.0,Male,Bhopal,Madhya Pradesh,Regular,Email Marketing,Yes,Platinum
4476,C004190,2026/05/01,999.0,Female,Coimbatore,Tamil Nadu,Student,Organic Search,No,NaN
7872,C007382,26/06/2026,999.0,Male,Kochi,Kerala,Regular,Organic Search,Yes,NaN
5137,C004794,11/10/2023,999.0,Male,Ludhiana,Punjab,Regular,Direct,Yes,Bronze
6204,C005796,2023-12-07,999.0,Male,Coimbatore,Tamil Nadu,Student,Paid Search,Yes,NaN
6702,C006275,09/02/2024,999.0,Female,Delhi,Delhi,Premium,Direct,No,NaN
893,C000833,2025-09-15,999.0,Male,Ahmedabad,Gujarat,Small Business,Affiliate,No,NaN
1704,C001588,24/05/2026,999.0,Female,Delhi,Delhi,Regular,Direct,No,Bronze
8068,C007565,2023-06-09,999.0,Female,Bhopal,Madhya Pradesh,Regular,Email Marketing,No,Platinum
12389,C011593,2023-07-10,999.0,NaN,Mumbai,Maharashtra,Small Business,Paid Social,Yes,Silver

In [52]:
df.head()

,customer_id,signup_date,age,gender,city,state,customer_segment,acquisition_channel,email_opt_in,loyalty_tier
0,C000001,2024-10-05,NaN,Male,Indore,Madhya Pradesh,Regular,Organic Search,Yes,Bronze
1,C000002,2025-02-26,23.0,Female,Hyderabad,Telangana,Regular,Paid Search,Yes,Bronze
2,C000003,2023-01-05,38.0,Male,Bengaluru,Karnataka,Small Business,Paid Social,Yes,No Tier
3,C000004,2025-10-02,NaN,Female,Lucknow,Uttar Pradesh,Regular,Paid Social,Yes,Bronze
4,C000005,2025-02-04,30.0,Female,Delhi,Delhi,Regular,Direct,Yes,Bronze

In [53]:
df = df[df['age']<99]

In [54]:
df[df['age']<18].sort_values('age')

,customer_id,signup_date,age,gender,city,state,customer_segment,acquisition_channel,email_opt_in,loyalty_tier
1327,C001239,2025-11-14,-3.0,Female,Bengaluru,Karnataka,Bargain Hunter,Organic Search,Yes,NaN
12152,C011375,2024-12-30,-3.0,Male,Kochi,NaN,Regular,Paid Social,No,NaN
10020,C009380,2024-09-08,-3.0,Female,NaN,Karnataka,Regular,Direct,No,Gold
9547,C008937,2024-04-05,-3.0,Male,Patna,Bihar,Bargain Hunter,Paid Social,No,Bronze
3181,C002962,2023-10-10,0.0,Male,Mumbai,Maharashtra,Regular,Referral,Yes,Platinum
72,C000065,2023-12-12,0.0,Male,Coimbatore,Tamil Nadu,Student,Paid Social,Yes,Bronze
1444,C001349,12/05/2023,0.0,Female,Jaipur,Rajasthan,Student,Email Marketing,Yes,Bronze
464,C000431,2025-10-06,0.0,Female,Pune,Maharashtra,Regular,Paid Social,Yes,Bronze
6988,C006544,2023-10-17,0.0,Female,Coimbatore,Tamil Nadu,Regular,Referral,No,Platinum
7147,C006695,2024-07-18,0.0,Male,Bengaluru,Karnataka,Small Business,Paid Social,Yes,Platinum
4373,C004093,2025-05-18,0.0,Male,Kolkata,West Bengal,Regular,Paid Search,No,Gold
7708,C007227,2024-11-06,0.0,Female,Ahmedabad,Gujarat,Regular,Organic Search,Yes,Bronze
8980,C008406,2025-10-26,0.0,Male,Visakhapatnam,Andhra Pradesh,Bargain Hunter,Paid Social,Yes,NaN
3823,C003569,2024-12-14,0.0,Female,Nashik,Maharashtra,Regular,NaN,Yes,Gold
3066,C002856,01/08/2025,0.0,Male,Agra,Uttar Pradesh,Premium,Paid Search,No,NaN
4184,C003914,2024-01-04,0.0,Male,Jodhpur,Rajasthan,NaN,Referral,No,NaN
11972,C011209,2024-03-25,0.0,Male,Chennai,Tamil Nadu,Regular,Affiliate,No,Bronze
12287,C011499,11-Feb-2025,0.0,Female,Thiruvananthapuram,Kerala,Premium,Paid Social,Yes,Platinum
7993,C007493,2024-10-16,5.0,Male,Nashik,Maharashtra,Small Business,Paid Social,No,NaN
8463,C007927,2023-05-05,5.0,Female,Kochi,Kerala,Small Business,Organic Search,Yes,Platinum
1516,C001415,2025-06-25,5.0,Male,NaN,Delhi,Small Business,Organic Search,No,Silver
6975,C006532,2026/04/16,5.0,Female,Mumbai,Maharashtra,Regular,Organic Search,Yes,Bronze
6530,C006110,2024-05-11,5.0,Male,Kanpur,Uttar Pradesh,Regular,NaN,Yes,Gold
11338,C010620,2025-11-19,5.0,Other,Kolkata,West Bengal,Regular,Direct,Yes,NaN
9192,C008603,2026-05-15,5.0,Male,Bengaluru,Rajasthan,Small Business,Paid Search,Yes,Bronze
8891,C008327,22/02/2023,5.0,Female,Patna,Bihar,Small Business,Organic Search,No,Bronze
8561,C008018,2023-05-10,5.0,Male,Gurugram,Haryana,Student,Paid Social,Yes,Platinum
6190,C005782,21/12/2023,5.0,Male,Nagpur,Maharashtra,Premium,Paid Search,No,Platinum
3080,C002870,09/05/2026,5.0,Male,Kolkata,West Bengal,Regular,Referral,Yes,NaN
1464,C001367,2026-05-27,5.0,Female,Mumbai,Maharashtra,Regular,Organic Search,Yes,Bronze
485,C000451,2025-07-30,5.0,Male,Jaipur,Rajasthan,Student,Affiliate,Yes,Bronze
554,C000514,2026/04/06,5.0,Male,Pune,Maharashtra,Regular,Referral,Yes,Bronze
12105,C011334,2025-07-14,5.0,Female,Bhubaneswar,Odisha,Regular,Email Marketing,Yes,Silver
11899,C011139,2024-04-04,5.0,Male,Bengaluru,Karnataka,Small Business,Affiliate,No,Platinum
8126,C007621,2025-07-12,12.0,Male,Hyderabad,Telangana,Bargain Hunter,Paid Social,Yes,NaN
6331,C005919,2026-01-05,12.0,Female,Kolkata,West Bengal,Regular,Organic Search,Yes,Bronze
5050,C004712,28/04/2024,12.0,Male,Mumbai,Maharashtra,Regular,Affiliate,No,Bronze
2154,C001999,2023-01-24,12.0,Male,Hyderabad,Telangana,Regular,Paid Social,No,Bronze
2207,C002049,12-Apr-2024,12.0,Female,Hyderabad,Telangana,Student,Referral,Yes,Platinum
3852,C003596,2025-01-27,12.0,Female,NaN,Delhi,Regular,Paid Search,No,Bronze
1243,C001160,2026-04-02,12.0,Female,Kochi,Kerala,Student,Paid Search,No,NaN
3902,C003645,2023-12-24,12.0,Male,Chandigarh,Chandigarh,Regular,Organic Search,Yes,Platinum
6320,C005909,2023-09-18,12.0,Female,Surat,Gujarat,Regular,Affiliate,No,NaN
9637,C009024,2026-04-24,12.0,Male,Delhi,Delhi,Small Business,Paid Search,Yes,Silver
9905,C009272,28/11/2025,12.0,Female,Kolkata,West Bengal,Regular,Email Marketing,Yes,Gold
9813,C009187,2025-03-19,12.0,Male,Delhi,Delhi,Bargain Hunter,Referral,Yes,Bronze
9721,C009103,2026-05-19,12.0,Male,Mumbai,Maharashtra,Bargain Hunter,Organic Search,No,Bronze
9920,C009285,2023/12/22,12.0,Female,Ahmedabad,Gujarat,Bargain Hunter,Direct,Yes,Bronze

In [55]:
df = df[df['age'] > 17]

In [56]:
df.describe()

                age
count  11316.000000
mean      30.913574
std        9.439162
min       18.000000
25%       24.000000
50%       30.000000
75%       37.000000
max       98.000000

In [57]:
df.isnull().sum()

customer_id               0
signup_date             147
age                       0
gender                  353
city                    368
state                   410
customer_segment        301
acquisition_channel     278
email_opt_in            230
loyalty_tier           2698
dtype: int64

In [58]:
df['signup_date'].isna().sum()
df['signup_date'].isna().mean()*100

np.float64(1.2990455991516436)

In [59]:
df['signup_date'].dtype

In [60]:
df['signup_date'] = pd.to_datetime(
    df['signup_date'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

In [61]:
df['signup_date'].isna().sum()

np.int64(187)

In [62]:
df[df['signup_date'].isna()].head()

,customer_id,signup_date,age,gender,city,state,customer_segment,acquisition_channel,email_opt_in,loyalty_tier
8,C000009,NaT,25.0,Other,Amritsar,Punjab,Bargain Hunter,Paid Social,Yes,Bronze
155,C000145,NaT,33.0,Male,Coimbatore,NaN,Regular,Organic Search,No,Silver
415,C000387,NaT,44.0,Male,Bengaluru,Karnataka,Premium,Affiliate,Yes,Bronze
571,C000531,NaT,49.0,Male,Kolkata,West Bengal,Bargain Hunter,Direct,No,Gold
666,C000621,NaT,19.0,Male,Pune,Maharashtra,Student,Affiliate,No,Bronze

In [63]:
df['gender'].value_counts(dropna=False)

gender
Male          5707
Female        5031
NaN            353
Other          217
Non-binary       8
Name: count, dtype: int64

In [64]:
df['city'].value_counts(dropna = False)

city
Mumbai                1108
Delhi                 1019
Bengaluru              965
Pune                   605
Chennai                596
Hyderabad              580
Kolkata                512
Ahmedabad              427
NaN                    368
Lucknow                314
Jaipur                 303
Surat                  302
Kochi                  254
Gurugram               242
Noida                  234
Indore                 233
Nagpur                 202
Chandigarh             201
Coimbatore             198
Visakhapatnam          195
Patna                  189
Vadodara               163
Bhopal                 161
Guwahati               159
Nashik                 152
Bhubaneswar            148
Ludhiana               145
Kanpur                 135
Amritsar               114
Mysuru                 113
Ranchi                 113
Thiruvananthapuram     110
Agra                   107
Madurai                105
Raipur                 102
Jodhpur                 97
Vasai-Virar             96
Dehradun                93
Varanasi                87
Panaji                  69
Name: count, dtype: int64

In [65]:
df.loc[df['city'].isna(), 'state'].value_counts(dropna=False)

state
Maharashtra       69
Karnataka         37
Tamil Nadu        35
Gujarat           31
Delhi             29
Uttar Pradesh     19
Telangana         19
Rajasthan         18
Kerala            17
West Bengal       13
NaN               12
Assam             11
Punjab            10
Chandigarh        10
Madhya Pradesh     9
Haryana            8
Andhra Pradesh     6
Odisha             5
Bihar              5
Jharkhand          2
Uttarakhand        1
Goa                1
Chhattisgarh       1
Name: count, dtype: int64

In [66]:
df.loc[df['state'].isna(),['city','state']].value_counts(dropna=False)

city                state
Mumbai              NaN      45
Bengaluru           NaN      35
Delhi               NaN      29
Kolkata             NaN      23
Hyderabad           NaN      22
Chennai             NaN      20
Pune                NaN      19
Jaipur              NaN      17
Ahmedabad           NaN      17
Nagpur              NaN      13
Indore              NaN      12
Lucknow             NaN      12
NaN                 NaN      12
Gurugram            NaN      11
Coimbatore          NaN      10
Kochi               NaN      10
Surat               NaN       8
Bhopal              NaN       7
Vasai-Virar         NaN       7
Noida               NaN       7
Guwahati            NaN       7
Ludhiana            NaN       6
Raipur              NaN       6
Bhubaneswar         NaN       6
Visakhapatnam       NaN       6
Vadodara            NaN       6
Nashik              NaN       5
Ranchi              NaN       5
Kanpur              NaN       5
Varanasi            NaN       4
Dehradun            NaN       4
Patna               NaN       4
Chandigarh          NaN       3
Madurai             NaN       1
Thiruvananthapuram  NaN       1
Mysuru              NaN       1
Jodhpur             NaN       1
Amritsar            NaN       1
Agra                NaN       1
Panaji              NaN       1
Name: count, dtype: int64

In [67]:
city_state_map = {
    'Mumbai': 'Maharashtra',
    'Bengaluru': 'Karnataka',
    'Delhi': 'Delhi',
    'Kolkata': 'West Bengal',
    'Hyderabad': 'Telangana',
    'Chennai': 'Tamil Nadu',
    'Pune': 'Maharashtra',
    'Jaipur': 'Rajasthan',
    'Ahmedabad': 'Gujarat',
    'Nagpur': 'Maharashtra',
    'Indore': 'Madhya Pradesh',
    'Lucknow': 'Uttar Pradesh',
    'Gurugram': 'Haryana',
    'Coimbatore': 'Tamil Nadu',
    'Kochi': 'Kerala',
    'Surat': 'Gujarat',
    'Bhopal': 'Madhya Pradesh',
    'Vasai-Virar': 'Maharashtra',
    'Noida': 'Uttar Pradesh',
    'Guwahati': 'Assam',
    'Ludhiana': 'Punjab',
    'Raipur': 'Chhattisgarh',
    'Bhubaneswar': 'Odisha',
    'Visakhapatnam': 'Andhra Pradesh',
    'Vadodara': 'Gujarat',
    'Nashik': 'Maharashtra',
    'Ranchi': 'Jharkhand',
    'Kanpur': 'Uttar Pradesh',
    'Varanasi': 'Uttar Pradesh',
    'Dehradun': 'Uttarakhand',
    'Patna': 'Bihar',
    'Chandigarh': 'Chandigarh',
    'Madurai': 'Tamil Nadu',
    'Thiruvananthapuram': 'Kerala',
    'Mysuru': 'Karnataka',
    'Jodhpur': 'Rajasthan',
    'Amritsar': 'Punjab',
    'Agra': 'Uttar Pradesh',
    'Panaji': 'Goa'
}

df['state'] = df['state'].fillna(df['city'].map(city_state_map))

In [68]:
df['state'].isna().sum()

np.int64(12)

In [69]:
[df['customer_segment'].value_counts(dropna=False)]

[customer_segment
 Regular           5037
 Bargain Hunter    1956
 Student           1780
 Premium           1317
 Small Business     876
 NaN                301
 Deal Seeker         49
 Name: count, dtype: int64]

In [70]:
df['acquisition_channel'].value_counts(dropna=False)

acquisition_channel
Organic Search     2679
Paid Social        2107
Paid Search        1865
Direct             1422
Referral           1084
Affiliate           997
Email Marketing     884
NaN                 278
Name: count, dtype: int64

In [71]:
df['email_opt_in'].value_counts(dropna=False)

email_opt_in
Yes     6873
No      4213
<NA>     230
Name: count, dtype: Int64

In [72]:
df['loyalty_tier'].value_counts(dropna=False)

loyalty_tier
Bronze      4358
NaN         2698
Gold        1488
Silver      1315
Platinum    1268
No Tier      189
Name: count, dtype: int64

In [73]:
df.loc[df['loyalty_tier'].isna(),['customer_segment','email_opt_in']].value_counts(dropna=False)

customer_segment  email_opt_in
Regular           Yes             728
                  No              431
Bargain Hunter    Yes             289
Student           Yes             261
Premium           Yes             196
Bargain Hunter    No              194
Student           No              142
Small Business    Yes             126
Premium           No              118
Small Business    No               81
NaN               Yes              36
                  No               28
Regular           <NA>             19
Bargain Hunter    <NA>             11
Small Business    <NA>             10
Deal Seeker       Yes               8
Premium           <NA>              7
Deal Seeker       No                6
Student           <NA>              6
NaN               <NA>              1
Name: count, dtype: int64

In [74]:
df.loc[
    df['loyalty_tier'].eq('No Tier'),
    ['customer_segment', 'email_opt_in']
].value_counts(dropna=False)

customer_segment  email_opt_in
Regular           Yes             60
                  No              27
Bargain Hunter    Yes             17
Student           No              16
                  Yes             15
Small Business    No              12
Premium           Yes             12
Bargain Hunter    No              10
Small Business    Yes              5
Premium           No               5
NaN               Yes              4
                  No               2
Regular           <NA>             2
Deal Seeker       No               1
Student           <NA>             1
Name: count, dtype: int64

In [75]:
missing_summary = df.isna().sum()

missing_summary = missing_summary[missing_summary > 0]

print(missing_summary.sort_values(ascending=False))

loyalty_tier           2698
city                    368
gender                  353
customer_segment        301
acquisition_channel     278
email_opt_in            230
signup_date             187
state                    12
dtype: int64

In [76]:
df.duplicated().sum()

np.int64(44)

In [77]:
df[df.duplicated(keep=False)].sort_values(
    by=df.columns.tolist()
)

,customer_id,signup_date,age,gender,city,state,customer_segment,acquisition_channel,email_opt_in,loyalty_tier
248,C000234,2026-03-06,29.0,Male,Hyderabad,Telangana,Regular,Organic Search,Yes,Bronze
4834,C000234,2026-03-06,29.0,Male,Hyderabad,Telangana,Regular,Organic Search,Yes,Bronze
263,C000249,2023-11-13,31.0,Female,Nagpur,Maharashtra,Bargain Hunter,Referral,Yes,Gold
3397,C000249,2023-11-13,31.0,Female,Nagpur,Maharashtra,Bargain Hunter,Referral,Yes,Gold
348,C000327,2024-09-07,33.0,Male,Bengaluru,Karnataka,Regular,Direct,No,Bronze
...,...,...,...,...,...,...,...,...,...,...
11635,C010894,2025-10-10,53.0,Male,Bengaluru,Karnataka,Regular,Direct,No,Bronze
2556,C011227,2024-11-12,22.0,Male,Noida,Uttar Pradesh,Bargain Hunter,Paid Search,Yes,Gold
11991,C011227,2024-11-12,22.0,Male,Noida,Uttar Pradesh,Bargain Hunter,Paid Search,Yes,Gold
7763,C011288,2023-01-14,45.0,Male,Coimbatore,Tamil Nadu,Regular,Organic Search,Yes,Bronze
12056,C011288,2023-01-14,45.0,Male,Coimbatore,Tamil Nadu,Regular,Organic Search,Yes,Bronze

In [78]:
df = df.drop_duplicates()

In [79]:
df.duplicated().sum()

np.int64(0)

In [80]:
df['customer_id'].duplicated().sum()

np.int64(148)

In [81]:
df[df['customer_id'].duplicated(keep=False)].sort_values('customer_id')

,customer_id,signup_date,age,gender,city,state,customer_segment,acquisition_channel,email_opt_in,loyalty_tier
2,C000003,2023-05-01,38.0,Male,Bengaluru,Karnataka,Small Business,Paid Social,Yes,No Tier
2318,C000003,2023-05-01,38.0,Male,Bengaluru,Karnataka,Small Business,NaN,Yes,No Tier
46,C000042,2025-11-23,18.0,Male,Thiruvananthapuram,Kerala,Regular,Paid Search,No,NaN
3010,C000042,2025-11-23,18.0,Male,Thiruvananthapuram,Kerala,Regular,Paid Search,No,No Tier
145,C000135,2025-06-14,29.0,Female,Mumbai,Maharashtra,Small Business,Paid Search,Yes,NaN
...,...,...,...,...,...,...,...,...,...,...
8435,C010671,2026-02-16,28.0,Male,Surat,Gujarat,Regular,NaN,No,NaN
9696,C010745,2024-07-03,51.0,Male,NaN,Delhi,Bargain Hunter,Paid Search,Yes,Bronze
5469,C010745,2024-07-03,51.0,Male,Delhi,Delhi,Bargain Hunter,Paid Search,Yes,Bronze
11930,C011170,2024-12-02,37.0,Male,Kanpur,Uttar Pradesh,Regular,Paid Search,Yes,Silver
7245,C011170,2024-12-02,37.0,Male,Kanpur,Uttar Pradesh,Regular,NaN,Yes,Silver

In [82]:
duplicate_customers = df[
    df['customer_id'].duplicated(keep=False)
].sort_values('customer_id')

duplicate_customers.head(10)

,customer_id,signup_date,age,gender,city,state,customer_segment,acquisition_channel,email_opt_in,loyalty_tier
2,C000003,2023-05-01,38.0,Male,Bengaluru,Karnataka,Small Business,Paid Social,Yes,No Tier
2318,C000003,2023-05-01,38.0,Male,Bengaluru,Karnataka,Small Business,NaN,Yes,No Tier
46,C000042,2025-11-23,18.0,Male,Thiruvananthapuram,Kerala,Regular,Paid Search,No,NaN
3010,C000042,2025-11-23,18.0,Male,Thiruvananthapuram,Kerala,Regular,Paid Search,No,No Tier
145,C000135,2025-06-14,29.0,Female,Mumbai,Maharashtra,Small Business,Paid Search,Yes,NaN
3946,C000135,2025-06-14,29.0,Female,Mumbai,Maharashtra,Small Business,NaN,Yes,NaN
152,C000142,2025-11-15,25.0,Male,Indore,Madhya Pradesh,Student,Paid Search,Yes,NaN
8836,C000142,2025-11-15,25.0,NaN,Indore,Madhya Pradesh,Student,Paid Search,Yes,NaN
212,C000200,2026-03-22,42.0,Male,Amritsar,Punjab,Small Business,Referral,Yes,Silver
241,C000200,2026-03-22,42.0,Male,NaN,Punjab,Small Business,Referral,Yes,Silver

In [83]:
df['customer_id'].value_counts(dropna=False)

customer_id
C002769    3
C006278    3
C000003    2
C003285    2
C003588    2
          ..
C011596    1
C011597    1
C011598    1
C011599    1
C011600    1
Name: count, Length: 11124, dtype: int64

In [84]:
df.groupby('customer_id')['city'].nunique()

customer_id
C000002    1
C000003    1
C000005    1
C000006    1
C000007    1
          ..
C011596    1
C011597    1
C011598    1
C011599    1
C011600    1
Name: city, Length: 11124, dtype: int64

In [85]:
city_counts = df.groupby('customer_id')['city'].nunique()

city_counts[city_counts > 1]

Series([], Name: city, dtype: int64)

In [86]:
df['city'] =df['city'].fillna(df.groupby('customer_id')['city'].transform('first'))

In [87]:
df[df['customer_id'].duplicated(keep=False)].sort_values('customer_id')

,customer_id,signup_date,age,gender,city,state,customer_segment,acquisition_channel,email_opt_in,loyalty_tier
2,C000003,2023-05-01,38.0,Male,Bengaluru,Karnataka,Small Business,Paid Social,Yes,No Tier
2318,C000003,2023-05-01,38.0,Male,Bengaluru,Karnataka,Small Business,NaN,Yes,No Tier
46,C000042,2025-11-23,18.0,Male,Thiruvananthapuram,Kerala,Regular,Paid Search,No,NaN
3010,C000042,2025-11-23,18.0,Male,Thiruvananthapuram,Kerala,Regular,Paid Search,No,No Tier
145,C000135,2025-06-14,29.0,Female,Mumbai,Maharashtra,Small Business,Paid Search,Yes,NaN
...,...,...,...,...,...,...,...,...,...,...
8435,C010671,2026-02-16,28.0,Male,Surat,Gujarat,Regular,NaN,No,NaN
9696,C010745,2024-07-03,51.0,Male,Delhi,Delhi,Bargain Hunter,Paid Search,Yes,Bronze
5469,C010745,2024-07-03,51.0,Male,Delhi,Delhi,Bargain Hunter,Paid Search,Yes,Bronze
11930,C011170,2024-12-02,37.0,Male,Kanpur,Uttar Pradesh,Regular,Paid Search,Yes,Silver
7245,C011170,2024-12-02,37.0,Male,Kanpur,Uttar Pradesh,Regular,NaN,Yes,Silver

In [88]:
state_count = df.groupby('customer_id')['state'].nunique()

state_count[state_count > 1]

customer_id
C004321    2
Name: state, dtype: int64

In [89]:

state_counts = df.groupby('customer_id')['state'].nunique()

conflicting_states = state_counts[state_counts > 1]

df[df['customer_id'].isin(conflicting_states.index)].sort_values('customer_id')

,customer_id,signup_date,age,gender,city,state,customer_segment,acquisition_channel,email_opt_in,loyalty_tier
4623,C004321,2026-03-18,51.0,Male,Hyderabad,Maharashtra,Premium,Direct,Yes,Bronze
9781,C004321,2026-03-18,51.0,Male,Hyderabad,Telangana,Premium,Direct,Yes,Bronze

In [90]:
df.loc[df['customer_id']=='C004321','state'] = 'Telangana'

In [91]:
df['state'] = df['state'].fillna(df.groupby('customer_id')['state'].transform('first'))

In [92]:
df.duplicated().sum()

np.int64(50)

In [93]:
age_count = df.groupby('customer_id')['age'].nunique()

conflicting_age = age_count[age_count > 1]

In [94]:
df[df['customer_id'].isin(conflicting_age.index)].sort_values('customer_id')

Empty DataFrame
Columns: [customer_id, signup_date, age, gender, city, state, customer_segment, acquisition_channel, email_opt_in, loyalty_tier]
Index: []

In [95]:
df['age'] = df['age'].fillna(df.groupby('customer_id')['age'].transform('first'))

In [96]:
df.duplicated().sum()

np.int64(50)

In [97]:
gender_count = df.groupby('customer_id')['gender'].nunique()

conflicting_gender = gender_count[gender_count > 1]

df[df['customer_id'].isin(conflicting_gender.index)].sort_values('customer_id')

Empty DataFrame
Columns: [customer_id, signup_date, age, gender, city, state, customer_segment, acquisition_channel, email_opt_in, loyalty_tier]
Index: []

In [98]:
df[df['gender'].isna()]

,customer_id,signup_date,age,gender,city,state,customer_segment,acquisition_channel,email_opt_in,loyalty_tier
58,C000858,2026-05-27,23.0,NaN,Nashik,Maharashtra,Bargain Hunter,Direct,Yes,NaN
59,C000053,2024-02-15,24.0,NaN,Indore,Madhya Pradesh,Student,Organic Search,Yes,NaN
77,C000070,2023-10-16,19.0,NaN,Kanpur,Uttar Pradesh,Student,Organic Search,Yes,Platinum
113,C000103,2026-03-24,23.0,NaN,Surat,Gujarat,Student,Direct,Yes,Bronze
160,C000150,2024-07-30,24.0,NaN,Pune,Maharashtra,Bargain Hunter,Affiliate,Yes,NaN
...,...,...,...,...,...,...,...,...,...,...
12272,C007541,2026-02-27,22.0,NaN,Agra,Uttar Pradesh,Bargain Hunter,Organic Search,Yes,NaN
12289,C011501,2025-04-24,33.0,NaN,Bhopal,Madhya Pradesh,Deal Seeker,Organic Search,No,Bronze
12300,C006399,2024-02-01,33.0,NaN,Chennai,Tamil Nadu,Regular,NaN,No,Bronze
12309,C011519,2026-03-13,38.0,NaN,Delhi,Delhi,Deal Seeker,Paid Social,Yes,Bronze
12379,C011583,2026-01-05,33.0,NaN,Bengaluru,Karnataka,Small Business,Referral,Yes,NaN

In [99]:
df['gender'] = df['gender'].fillna(df.groupby('customer_id')['gender'].transform('first'))

In [100]:
customer_segment_count = df.groupby('customer_id')['gender'].nunique()

conflicting_customer_segment = customer_segment_count[customer_segment_count > 1]

df[df['customer_id'].isin(conflicting_customer_segment.index)].sort_values('customer_id')

Empty DataFrame
Columns: [customer_id, signup_date, age, gender, city, state, customer_segment, acquisition_channel, email_opt_in, loyalty_tier]
Index: []

In [101]:
df['customer_segment'] = df['customer_segment'].fillna(df.groupby('customer_id')['customer_segment'].transform('first'))

In [102]:
df = df.drop_duplicates()

In [103]:
df[df['customer_id'].duplicated(keep=False)].sort_values('customer_id')

,customer_id,signup_date,age,gender,city,state,customer_segment,acquisition_channel,email_opt_in,loyalty_tier
2,C000003,2023-05-01,38.0,Male,Bengaluru,Karnataka,Small Business,Paid Social,Yes,No Tier
2318,C000003,2023-05-01,38.0,Male,Bengaluru,Karnataka,Small Business,NaN,Yes,No Tier
3010,C000042,2025-11-23,18.0,Male,Thiruvananthapuram,Kerala,Regular,Paid Search,No,No Tier
46,C000042,2025-11-23,18.0,Male,Thiruvananthapuram,Kerala,Regular,Paid Search,No,NaN
3946,C000135,2025-06-14,29.0,Female,Mumbai,Maharashtra,Small Business,NaN,Yes,NaN
...,...,...,...,...,...,...,...,...,...,...
2691,C009808,2025-10-08,40.0,Female,Delhi,Delhi,Small Business,NaN,Yes,Bronze
8435,C010671,2026-02-16,28.0,Male,Surat,Gujarat,Regular,NaN,No,NaN
11393,C010671,2026-02-16,28.0,Male,Surat,Gujarat,Regular,Paid Social,No,NaN
11930,C011170,2024-12-02,37.0,Male,Kanpur,Uttar Pradesh,Regular,Paid Search,Yes,Silver
7245,C011170,2024-12-02,37.0,Male,Kanpur,Uttar Pradesh,Regular,NaN,Yes,Silver

In [104]:
segment_counts = df.groupby('customer_id')['customer_segment'].nunique()

segment_conflicts = segment_counts[segment_counts > 1]

df[df['customer_id'].isin(segment_conflicts.index)].sort_values('customer_id')

Empty DataFrame
Columns: [customer_id, signup_date, age, gender, city, state, customer_segment, acquisition_channel, email_opt_in, loyalty_tier]
Index: []

In [105]:
df['customer_segment'] = df['customer_segment'].fillna(
    df.groupby('customer_id')['customer_segment'].transform('first')
)

In [106]:
df.duplicated().sum()

np.int64(0)

In [107]:
acquisition_channel_counts = df.groupby('customer_id')['acquisition_channel'].nunique()

acquisition_channel_conflicts = acquisition_channel_counts[acquisition_channel_counts > 1]

df[df['customer_id'].isin(acquisition_channel_conflicts.index)].sort_values('customer_id')

Empty DataFrame
Columns: [customer_id, signup_date, age, gender, city, state, customer_segment, acquisition_channel, email_opt_in, loyalty_tier]
Index: []

In [108]:
df['acquisition_channel'] = df['acquisition_channel'].fillna(df.groupby
    ('customer_id')['acquisition_channel'].transform('first'))

In [109]:
df[df['customer_id'].duplicated(keep = False)].sort_values('customer_id')

,customer_id,signup_date,age,gender,city,state,customer_segment,acquisition_channel,email_opt_in,loyalty_tier
2,C000003,2023-05-01,38.0,Male,Bengaluru,Karnataka,Small Business,Paid Social,Yes,No Tier
2318,C000003,2023-05-01,38.0,Male,Bengaluru,Karnataka,Small Business,Paid Social,Yes,No Tier
3010,C000042,2025-11-23,18.0,Male,Thiruvananthapuram,Kerala,Regular,Paid Search,No,No Tier
46,C000042,2025-11-23,18.0,Male,Thiruvananthapuram,Kerala,Regular,Paid Search,No,NaN
3946,C000135,2025-06-14,29.0,Female,Mumbai,Maharashtra,Small Business,Paid Search,Yes,NaN
...,...,...,...,...,...,...,...,...,...,...
2691,C009808,2025-10-08,40.0,Female,Delhi,Delhi,Small Business,Referral,Yes,Bronze
8435,C010671,2026-02-16,28.0,Male,Surat,Gujarat,Regular,Paid Social,No,NaN
11393,C010671,2026-02-16,28.0,Male,Surat,Gujarat,Regular,Paid Social,No,NaN
11930,C011170,2024-12-02,37.0,Male,Kanpur,Uttar Pradesh,Regular,Paid Search,Yes,Silver
7245,C011170,2024-12-02,37.0,Male,Kanpur,Uttar Pradesh,Regular,Paid Search,Yes,Silver

In [110]:
df = df.drop_duplicates()

In [111]:
df.duplicated().sum()

np.int64(0)

In [112]:
df[df['customer_id'].duplicated(keep = False)].sort_values('customer_id')

,customer_id,signup_date,age,gender,city,state,customer_segment,acquisition_channel,email_opt_in,loyalty_tier
46,C000042,2025-11-23,18.0,Male,Thiruvananthapuram,Kerala,Regular,Paid Search,No,NaN
3010,C000042,2025-11-23,18.0,Male,Thiruvananthapuram,Kerala,Regular,Paid Search,No,No Tier
1188,C001107,2025-10-23,38.0,Male,Bengaluru,Karnataka,NaN,Organic Search,No,NaN
1791,C001107,2025-10-23,38.0,Male,Bengaluru,Karnataka,NaN,Organic Search,No,No Tier
1907,C001777,2023-05-04,24.0,Female,Amritsar,Punjab,Student,Affiliate,Yes,NaN
7183,C001777,2023-05-04,24.0,Female,Amritsar,Punjab,Student,Affiliate,Yes,No Tier
2558,C002381,2026-06-02,24.0,Female,Chennai,Tamil Nadu,Student,Referral,No,NaN
5447,C002381,2026-06-02,24.0,Female,Chennai,Tamil Nadu,Student,Referral,No,No Tier
12014,C003599,2023-02-03,30.0,Male,Bhopal,Madhya Pradesh,Bargain Hunter,Paid Social,No,No Tier
3855,C003599,2023-02-03,30.0,Male,Bhopal,Madhya Pradesh,Bargain Hunter,Paid Social,No,NaN
8442,C003894,2026-06-17,20.0,Female,Jaipur,Rajasthan,Student,Organic Search,Yes,No Tier
4164,C003894,2026-06-17,20.0,Female,Jaipur,Rajasthan,Student,Organic Search,Yes,NaN
5750,C005369,2025-03-08,27.0,Female,Delhi,Delhi,Premium,Direct,Yes,NaN
10787,C005369,2025-03-08,27.0,Female,Delhi,Delhi,Premium,Direct,Yes,No Tier
8666,C005831,2025-08-14,18.0,Female,Visakhapatnam,Andhra Pradesh,Regular,Organic Search,No,No Tier
6240,C005831,2025-08-14,18.0,Female,Visakhapatnam,Andhra Pradesh,Regular,Organic Search,No,NaN
6642,C006220,2025-03-07,26.0,Female,NaN,Chandigarh,Regular,Paid Social,Yes,NaN
5702,C006220,2025-03-07,26.0,Female,NaN,Chandigarh,Regular,Paid Social,Yes,No Tier
6816,C006278,2025-01-05,22.0,Male,Delhi,Delhi,Student,Affiliate,Yes,No Tier
6705,C006278,2025-01-05,22.0,Male,Delhi,Delhi,Student,Affiliate,Yes,NaN
10220,C006373,2025-12-01,23.0,NaN,Chennai,Tamil Nadu,Student,Paid Search,No,No Tier
6807,C006373,2025-12-01,23.0,NaN,Chennai,Tamil Nadu,Student,Paid Search,No,NaN
9548,C008938,2023-11-25,29.0,Female,Hyderabad,Telangana,Small Business,Paid Social,No,NaN
2851,C008938,2023-11-25,29.0,Female,Hyderabad,Telangana,Small Business,Paid Social,No,No Tier
7195,C009132,2024-07-01,43.0,Male,Coimbatore,Tamil Nadu,Bargain Hunter,Email Marketing,No,No Tier
9752,C009132,2024-07-01,43.0,Male,Coimbatore,Tamil Nadu,Bargain Hunter,Email Marketing,No,NaN

In [113]:
tier_counts = df.groupby('customer_id')['loyalty_tier'].nunique()

tier_conflicts = tier_counts[tier_counts > 1]

df[df['customer_id'].isin(tier_conflicts.index)].sort_values('customer_id')

Empty DataFrame
Columns: [customer_id, signup_date, age, gender, city, state, customer_segment, acquisition_channel, email_opt_in, loyalty_tier]
Index: []

In [114]:
df['loyalty_tier'] = df['loyalty_tier'].fillna(df.groupby(
    'customer_id')['loyalty_tier'].transform('first')
)

In [115]:
df = df.drop_duplicates()

In [116]:
df[df['customer_id'].duplicated(keep = False)].sort_values('customer_id')

Empty DataFrame
Columns: [customer_id, signup_date, age, gender, city, state, customer_segment, acquisition_channel, email_opt_in, loyalty_tier]
Index: []

In [117]:
df.info()

<class 'pandas.DataFrame'>
Index: 11124 entries, 1 to 12398
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          11124 non-null  str
 1   signup_date          10937 non-null  datetime64[us]
 2   age                  11124 non-null  float64
 3   gender               10821 non-null  str
 4   city                 10810 non-null  str
 5   state                11114 non-null  str
 6   customer_segment     10831 non-null  str
 7   acquisition_channel  10888 non-null  str
 8   email_opt_in         10899 non-null  string
 9   loyalty_tier         8487 non-null   str
dtypes: datetime64[us](1), float64(1), str(7), string(1)
memory usage: 956.0 KB

In [118]:
df['age'] = df['age'].astype('Int64')

In [119]:
df['email_opt_in'] = df['email_opt_in'].map({
    'Yes' : True,
    'No' : False
}).astype('boolean')

In [120]:
df['gender'].value_counts(dropna=False)

gender
Male          5629
Female        4970
NaN            303
Other          214
Non-binary       8
Name: count, dtype: int64

In [121]:
df.to_csv('../Data/Cleaned/customers_cleaned.csv', index=False)

In [122]:
df = pd.read_csv('customers_cleaned.csv')

In [123]:
df.isnull().sum()

customer_id               0
signup_date             187
age                       0
gender                  303
city                    314
state                    10
customer_segment        293
acquisition_channel     236
email_opt_in            225
loyalty_tier           2637
dtype: int64